package core.src.Class;

public class timetable extends javax.swing.JFrame {

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cell2 = new core.src.Class.Cell();
        Mon = new core.src.Class.Cell();
        cell3 = new core.src.Class.Cell();
        cell4 = new core.src.Class.Cell();
        cell5 = new core.src.Class.Cell();
        cell6 = new core.src.Class.Cell();
        cell7 = new core.src.Class.Cell();
        cell8 = new core.src.Class.Cell();
        Mon8 = new core.src.Class.Cell();
        Cell cell10 = new Cell();
        cell11 = new core.src.Class.Cell();
        cell12 = new core.src.Class.Cell();
        cell13 = new core.src.Class.Cell();
        cell14 = new core.src.Class.Cell();
        cell15 = new core.src.Class.Cell();
        Mon9 = new core.src.Class.Cell();
        cell17 = new core.src.Class.Cell();
        cell18 = new core.src.Class.Cell();
        cell19 = new core.src.Class.Cell();
        cell20 = new core.src.Class.Cell();
        cell21 = new core.src.Class.Cell();
        cell22 = new core.src.Class.Cell();
        cell23 = new core.src.Class.Cell();
        cell24 = new core.src.Class.Cell();
        cell25 = new core.src.Class.Cell();
        cell26 = new core.src.Class.Cell();
        cell27 = new core.src.Class.Cell();
        cell28 = new core.src.Class.Cell();
        cell29 = new core.src.Class.Cell();
        cell30 = new core.src.Class.Cell();
        cell31 = new core.src.Class.Cell();
        cell32 = new core.src.Class.Cell();
        cell33 = new core.src.Class.Cell();
        cell34 = new core.src.Class.Cell();
        Cell cell35 = new Cell();
        cell36 = new core.src.Class.Cell();
        cell37 = new core.src.Class.Cell();
        cell38 = new core.src.Class.Cell();
        cell39 = new core.src.Class.Cell();
        cell40 = new core.src.Class.Cell();
        cell41 = new core.src.Class.Cell();
        cell42 = new core.src.Class.Cell();
        cell43 = new core.src.Class.Cell();
        cell44 = new core.src.Class.Cell();
        cell45 = new core.src.Class.Cell();
        cell46 = new core.src.Class.Cell();
        cell47 = new core.src.Class.Cell();
        cell48 = new core.src.Class.Cell();
        cell49 = new core.src.Class.Cell();
        cell50 = new core.src.Class.Cell();
        cell51 = new core.src.Class.Cell();
        cell52 = new core.src.Class.Cell();
        cell53 = new core.src.Class.Cell();
        cell54 = new core.src.Class.Cell();
        cell55 = new core.src.Class.Cell();
        cell56 = new core.src.Class.Cell();
        cell57 = new core.src.Class.Cell();
        cell58 = new core.src.Class.Cell();
        cell59 = new core.src.Class.Cell();
        cell60 = new core.src.Class.Cell();
        cell61 = new core.src.Class.Cell();
        cell62 = new core.src.Class.Cell();
        cell63 = new core.src.Class.Cell();
        cell64 = new core.src.Class.Cell();
        cell65 = new core.src.Class.Cell();
        cell66 = new core.src.Class.Cell();
        cell67 = new core.src.Class.Cell();
        cell68 = new core.src.Class.Cell();
        cell69 = new core.src.Class.Cell();
        cell70 = new core.src.Class.Cell();
        cell71 = new core.src.Class.Cell();
        cell72 = new core.src.Class.Cell();
        cell73 = new core.src.Class.Cell();
        cell74 = new core.src.Class.Cell();
        cell75 = new core.src.Class.Cell();
        cell76 = new core.src.Class.Cell();
        cell77 = new core.src.Class.Cell();
        cell78 = new core.src.Class.Cell();
        cell79 = new core.src.Class.Cell();
        cell80 = new core.src.Class.Cell();
        cell81 = new core.src.Class.Cell();
        cell82 = new core.src.Class.Cell();
        cell83 = new core.src.Class.Cell();
        cell84 = new core.src.Class.Cell();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(13, 7));

        cell2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell2ActionPerformed(evt);
            }
        });
        jPanel2.add(cell2);

        Mon.setText("Mon");
        Mon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(Mon);

        cell3.setText("Tue");
        cell3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell3);

        cell4.setText("Wed");
        cell4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell4);

        cell5.setText("Thu");
        cell5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell5);

        cell6.setText("Fri");
        cell6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell6ActionPerformed(evt);
            }
        });
        jPanel2.add(cell6);

        cell7.setText("Sat");
        cell7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell7);

        cell8.setText("8");
        cell8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell8);
        jPanel2.add(Mon8);
        jPanel2.add(cell10);
        jPanel2.add(cell11);
        jPanel2.add(cell12);
        jPanel2.add(cell13);
        jPanel2.add(cell14);

        cell15.setText("9");
        cell15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell15);
        jPanel2.add(Mon9);
        jPanel2.add(cell17);
        jPanel2.add(cell18);
        jPanel2.add(cell19);
        jPanel2.add(cell20);
        jPanel2.add(cell21);

        cell22.setText("10");
        cell22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell22);
        jPanel2.add(cell23);
        jPanel2.add(cell24);
        jPanel2.add(cell25);
        jPanel2.add(cell26);
        jPanel2.add(cell27);
        jPanel2.add(cell28);

        cell29.setText("11");
        cell29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell29);
        jPanel2.add(cell30);
        jPanel2.add(cell31);
        jPanel2.add(cell32);
        jPanel2.add(cell33);
        jPanel2.add(cell34);
        jPanel2.add(cell35);

        cell36.setText("12");
        cell36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell36ActionPerformed(evt);
            }
        });
        jPanel2.add(cell36);
        jPanel2.add(cell37);
        jPanel2.add(cell38);
        jPanel2.add(cell39);
        jPanel2.add(cell40);
        jPanel2.add(cell41);
        jPanel2.add(cell42);

        cell43.setText("1");
        cell43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell43);
        jPanel2.add(cell44);
        jPanel2.add(cell45);
        jPanel2.add(cell46);
        jPanel2.add(cell47);
        jPanel2.add(cell48);
        jPanel2.add(cell49);

        cell50.setText("2");
        cell50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell50);
        jPanel2.add(cell51);
        jPanel2.add(cell52);
        jPanel2.add(cell53);
        jPanel2.add(cell54);
        jPanel2.add(cell55);
        jPanel2.add(cell56);

        cell57.setText("3");
        cell57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell57);
        jPanel2.add(cell58);
        jPanel2.add(cell59);
        jPanel2.add(cell60);
        jPanel2.add(cell61);
        jPanel2.add(cell62);
        jPanel2.add(cell63);

        cell64.setText("4");
        cell64.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell64);
        jPanel2.add(cell65);
        jPanel2.add(cell66);
        jPanel2.add(cell67);
        jPanel2.add(cell68);
        jPanel2.add(cell69);
        jPanel2.add(cell70);

        cell71.setText("5");
        cell71.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell71);
        jPanel2.add(cell72);
        jPanel2.add(cell73);
        jPanel2.add(cell74);
        jPanel2.add(cell75);
        jPanel2.add(cell76);
        jPanel2.add(cell77);

        cell78.setText("6");
        cell78.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell78);
        jPanel2.add(cell79);
        jPanel2.add(cell80);
        jPanel2.add(cell81);
        jPanel2.add(cell82);
        jPanel2.add(cell83);
        jPanel2.add(cell84);

        jButton1.setText("Add class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell2ActionPerformed

    private void cell6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell6ActionPerformed

    private void cell36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell36ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new addClass().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new removeClass().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private core.src.Class.Cell Mon;
    private core.src.Class.Cell Mon8;
    private core.src.Class.Cell Mon9;
    private core.src.Class.Cell cell10;
    private core.src.Class.Cell cell11;
    private core.src.Class.Cell cell12;
    private core.src.Class.Cell cell13;
    private core.src.Class.Cell cell14;
    private core.src.Class.Cell cell15;
    private core.src.Class.Cell cell17;
    private core.src.Class.Cell cell18;
    private core.src.Class.Cell cell19;
    private core.src.Class.Cell cell2;
    private core.src.Class.Cell cell20;
    private core.src.Class.Cell cell21;
    private core.src.Class.Cell cell22;
    private core.src.Class.Cell cell23;
    private core.src.Class.Cell cell24;
    private core.src.Class.Cell cell25;
    private core.src.Class.Cell cell26;
    private core.src.Class.Cell cell27;
    private core.src.Class.Cell cell28;
    private core.src.Class.Cell cell29;
    private core.src.Class.Cell cell3;
    private core.src.Class.Cell cell30;
    private core.src.Class.Cell cell31;
    private core.src.Class.Cell cell32;
    private core.src.Class.Cell cell33;
    private core.src.Class.Cell cell34;
    private core.src.Class.Cell cell35;
    private core.src.Class.Cell cell36;
    private core.src.Class.Cell cell37;
    private core.src.Class.Cell cell38;
    private core.src.Class.Cell cell39;
    private core.src.Class.Cell cell4;
    private core.src.Class.Cell cell40;
    private core.src.Class.Cell cell41;
    private core.src.Class.Cell cell42;
    private core.src.Class.Cell cell43;
    private core.src.Class.Cell cell44;
    private core.src.Class.Cell cell45;
    private core.src.Class.Cell cell46;
    private core.src.Class.Cell cell47;
    private core.src.Class.Cell cell48;
    private core.src.Class.Cell cell49;
    private core.src.Class.Cell cell5;
    private core.src.Class.Cell cell50;
    private core.src.Class.Cell cell51;
    private core.src.Class.Cell cell52;
    private core.src.Class.Cell cell53;
    private core.src.Class.Cell cell54;
    private core.src.Class.Cell cell55;
    private core.src.Class.Cell cell56;
    private core.src.Class.Cell cell57;
    private core.src.Class.Cell cell58;
    private core.src.Class.Cell cell59;
    private core.src.Class.Cell cell6;
    private core.src.Class.Cell cell60;
    private core.src.Class.Cell cell61;
    private core.src.Class.Cell cell62;
    private core.src.Class.Cell cell63;
    private core.src.Class.Cell cell64;
    private core.src.Class.Cell cell65;
    private core.src.Class.Cell cell66;
    private core.src.Class.Cell cell67;
    private core.src.Class.Cell cell68;
    private core.src.Class.Cell cell69;
    private core.src.Class.Cell cell7;
    private core.src.Class.Cell cell70;
    private core.src.Class.Cell cell71;
    private core.src.Class.Cell cell72;
    private core.src.Class.Cell cell73;
    private core.src.Class.Cell cell74;
    private core.src.Class.Cell cell75;
    private core.src.Class.Cell cell76;
    private core.src.Class.Cell cell77;
    private core.src.Class.Cell cell78;
    private core.src.Class.Cell cell79;
    private core.src.Class.Cell cell8;
    private core.src.Class.Cell cell80;
    private core.src.Class.Cell cell81;
    private core.src.Class.Cell cell82;
    private core.src.Class.Cell cell83;
    private core.src.Class.Cell cell84;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}